import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy — Ugent',
}

export default function PrivacyPage() {
  return (
    <main className="min-h-screen px-4 py-16">
      <div className="max-w-2xl mx-auto card p-8 space-y-6">
        <header>
          <h1 className="text-3xl font-bold text-neutral-900">Privacy Policy</h1>
          <p className="text-sm text-neutral-500 mt-1">Last updated: August 2026</p>
        </header>

        <section>
          <h2>1. What we collect</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>Account data</strong> — your email address and password (stored
              securely by our authentication provider).
            </li>
            <li>
              <strong>Study data</strong> — quiz attempts, scores, answers, and completed
              curriculum blocks, tied to your account so your progress and analytics
              persist.
            </li>
            <li>
              <strong>Chat data</strong> — messages you send to Clea, our AI study
              assistant, including voice recordings, which are transcribed to text to
              generate answers.
            </li>
            <li>
              <strong>Local data</strong> — flashcard mastery, leaderboard identity, and
              UI preferences are stored on your device via localStorage. Completed
              curriculum blocks are synced to your account.
            </li>
          </ul>
        </section>

        <section>
          <h2>2. Voice recordings</h2>
          <p>
            When you use voice mode, your audio is sent to a transcription service (OpenAI
            whisper) to convert speech to text. The resulting text is used only to answer
            your question and is retained as part of your chat history. Audio files
            themselves are not stored. Text-to-speech replies are generated by a voice
            provider (ElevenLabs); the generated audio is streamed to your device and is
            not stored.
          </p>
        </section>

        <section>
          <h2>3. Third parties</h2>
          <ul className="list-disc pl-5 space-y-1">
            <li>
              <strong>Supabase</strong> — authentication, database, and hosting of account
              and study data.
            </li>
            <li>
              <strong>OpenAI</strong> — transcription of voice input and, in some cases,
              chat answer generation.
            </li>
            <li>
              <strong>ElevenLabs</strong> — text-to-speech generation for Clea&apos;s spoken
              replies.
            </li>
            <li>
              <strong>Vercel</strong> — application hosting and delivery.
            </li>
          </ul>
          <p className="mt-2">
            Each provider processes data only to provide its service. We do not sell your
            personal data.
          </p>
        </section>

        <section>
          <h2>4. Cookies and local storage</h2>
          <p>
            We use authentication cookies required for you to stay signed in, and browser
            localStorage to persist study preferences and progress. We do not use
            third-party advertising or tracking cookies.
          </p>
        </section>

        <section>
          <h2>5. How long we keep data</h2>
          <p>
            Account, study, and chat data are kept while your account is active. You can
            delete your account at any time to remove this data. Local-only data (block
            progress, flashcards) is removed if you clear your browser storage.
          </p>
        </section>

        <section>
          <h2>6. Your rights</h2>
          <p>
            Depending on your jurisdiction (including under the GDPR), you may have the
            right to access, correct, export, or delete your personal data, and to
            withdraw consent for processing. To exercise these rights, email us from the
            address on your account.
          </p>
        </section>

        <section>
          <h2>7. Data transfers</h2>
          <p>
            Your data is processed by providers located in the United States and the
            European Union. Where data crosses borders, we rely on the providers&apos;
            standard contractual clauses or equivalent safeguards.
          </p>
        </section>

        <section>
          <h2>8. Contact</h2>
          <p>
            For privacy questions, requests, or complaints, email us from the address on
            your account. We aim to respond within 30 days.
          </p>
        </section>

        <footer className="text-sm text-neutral-500 pt-2 border-t border-neutral-200">
          Read our{' '}
          <Link href="/terms" className="text-primary-600 font-medium hover:underline">
            Terms of Service
          </Link>
          .
        </footer>
      </div>
    </main>
  )
}
