"""Builds components/hub/body/body-art.generated.ts from the EMBL-EBI Expression Atlas anatomogram body SVGs
(@ebi-gene-expression-group/anatomogram 2.4.0: code Apache-2.0, images CC BY 4.0, credit required, see components/hub/Credits).
Keeps the body outline and the organs the hub uses, strips Inkscape metadata and styles (the hub styles them),
rounds coordinates. Usage: python3 scripts/build-body-assets.py <dir with male.svg and female.svg>"""
import json, re, sys, xml.etree.ElementTree as ET

SRC = sys.argv[1]
NS = {'svg': 'http://www.w3.org/2000/svg'}
ET.register_namespace('', NS['svg'])
KEEP = {  # UBERON id -> short key used by the hub
    'UBERON_0000955': 'brain', 'UBERON_0002037': 'cerebellum', 'UBERON_0000970': 'eye', 'UBERON_0000948': 'heart',
    'UBERON_0002048': 'lung', 'UBERON_0000310': 'breast', 'UBERON_0002369': 'adrenal',
    'UBERON_0002113': 'kidney', 'UBERON_0000473': 'testis', 'UBERON_0000995': 'uterus', 'UBERON_0000992': 'ovary',
    'UBERON_0000002': 'cervix', 'UBERON_0003889': 'fallopian-tube',
}
SPLIT = {'lung', 'kidney', 'adrenal', 'ovary', 'eye'}  # paired organs: emitted as <key>-vl / <key>-vr (viewer's left / right)
DROP_ATTR = re.compile(r'^(\{http://(www\.inkscape\.org|sodipodi\.sourceforge\.net|www\.w3\.org/1999/xlink)[^}]*\}.*|style|class|id)$')
NUM = re.compile(r'-?\d+\.\d{3,}')

def r1(m): return f'{float(m.group()):.1f}'
def r3(m): return f'{float(m.group()):.3f}'.rstrip('0').rstrip('.')

def clean(el, keep_id=False):
    for a in list(el.attrib):
        if a == 'id' and keep_id: continue
        if a == 'd': el.attrib[a] = NUM.sub(r1, el.attrib[a]); continue
        if a == 'transform': el.attrib[a] = NUM.sub(r3, el.attrib[a]); continue
        if DROP_ATTR.match(a) or a.startswith('{'): del el.attrib[a]
    for c in list(el):
        tag = c.tag.split('}')[-1]
        if tag in ('title', 'metadata', 'defs', 'namedview', 'desc'): el.remove(c); continue
        clean(c)

def first_x(g, path):
    x, y = map(float, re.match(r'M\s*(-?[\d.]+)[ ,]+(-?[\d.]+)', path.get('d')).groups())
    t = g.get('transform') or ''
    m = re.match(r'translate\(([-\d.]+),([-\d.]+)\)', t)
    if m: return x + float(m.group(1))
    m = re.match(r'matrix\(([-\d.]+),([-\d.]+),([-\d.]+),([-\d.]+),([-\d.]+),([-\d.]+)\)', t)
    if m: a, _, c, _, e, _ = map(float, m.groups()); return a * x + c * y + e
    return x

def ser(el):
    s = ET.tostring(el, encoding='unicode')
    return re.sub(r'\s+xmlns(:\w+)?="[^"]+"', '', s)

out = {}
for sex in ('male', 'female'):
    root = ET.parse(f'{SRC}/{sex}.svg').getroot()
    vb = [round(float(x), 2) for x in root.get('viewBox').split()][2:]
    outline = next(g for g in root.iter('{%s}g' % NS['svg']) if g.get('id') == 'LAYER_OUTLINE')
    clean(outline)
    for el in list(outline):  # the atlas logo is an <a> link in the outline layer
        if el.tag.split('}')[-1] == 'a': outline.remove(el)
    organs = {}
    for g in root.iter('{%s}g' % NS['svg']):
        gid = g.get('id')
        if gid in KEEP:
            title = g.find('svg:title', NS)
            name = title.text if title is not None else KEEP[gid]
            clean(g)
            key = KEEP[gid]
            kids = [c for c in g if c.tag.split('}')[-1] == 'path']
            if key in SPLIT and len(kids) == 2:
                kids.sort(key=lambda c: first_x(g, c))
                for side, kid in zip(('vl', 'vr'), kids):
                    ng = ET.Element(g.tag, {k: v for k, v in g.attrib.items()})
                    ng.append(kid)
                    organs[f'{key}-{side}'] = {'name': name, 'markup': ser(ng)}
            else:
                organs[key] = {'name': name, 'markup': ser(g)}
    out[sex] = {'viewBox': vb, 'outline': ser(outline), 'organs': organs}
    print(sex, 'viewBox', vb, 'outline', len(out[sex]['outline']), 'organs', {k: len(v['markup']) for k, v in organs.items()})

ts = '/* Generated by scripts/build-body-assets.py. Do not edit. Artwork: EMBL-EBI Expression Atlas anatomogram, CC BY 4.0. */\n'
ts += 'export interface BodyArt { viewBox: [number, number]; outline: string; organs: Record<string, { name: string; markup: string }> }\n'
ts += 'export const BODY_ART: Record<\'male\' | \'female\', BodyArt> = ' + json.dumps(out, separators=(',', ':')) + ' as Record<\'male\' | \'female\', BodyArt>;\n'
open('components/hub/body/body-art.generated.ts', 'w').write(ts)
print('written', len(ts), 'bytes')
